#!/usr/bin/env node
// SPDX-License-Identifier: MIT
//
// export-abis.mjs — auto-include ABIs from deployment, bankoneth-style.
//
// Reads Foundry build artifacts (out/<Contract>.sol/<Contract>.json) and, when present,
// the latest broadcast (broadcast/<Script>/<chainId>/run-latest.json), and emits under
// faicey/dapp/:
//   • abis/<Contract>.abi.js     — the ABI + method selectors as an importable ES module
//                                  ("imported like a stylesheet"; swap the file per contract)
//   • deployments/<chainId>.json — { <Contract>: "0x..." } addresses (kept OUT of the abi)
//   • contracts.json             — manifest the UI loads (no addresses)
//
// The abi.js carries NO address; a redeploy only rewrites deployments/<chainId>.json, so the
// UI never changes. Run after `forge build` (and optionally after a broadcast deploy):
//   node script/export-abis.mjs
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "out");
const BROADCAST = join(ROOT, "broadcast");
const DAPP = join(ROOT, "..", "dapp");
const ABI_DIR = join(DAPP, "abis");
const DEPLOY_DIR = join(DAPP, "deployments");

// Contracts to expose in the dApp. Add a line per contract — that is the only edit a new
// contract needs; the UI reads everything else from the generated abi.js.
const CONTRACTS = [
  { name: "SoundWaveToken", sol: "SoundWaveToken.sol" },
  { name: "JaimlaVoiceNFT", sol: "JaimlaVoiceNFT.sol" },
];

mkdirSync(ABI_DIR, { recursive: true });
mkdirSync(DEPLOY_DIR, { recursive: true });

function loadArtifact(c) {
  const p = join(OUT, c.sol, `${c.name}.json`);
  if (!existsSync(p)) return null;
  return JSON.parse(readFileSync(p, "utf8"));
}

const manifest = { generatedFrom: "forge out/", contracts: [] };

for (const c of CONTRACTS) {
  const art = loadArtifact(c);
  if (!art) {
    console.warn(`[export-abis] skip ${c.name} — run \`forge build\` first (no artifact)`);
    continue;
  }
  const abi = art.abi;
  // selectors so the browser never needs keccak: signature -> 4-byte selector
  const selectors = art.methodIdentifiers || {};
  const body =
    `// AUTO-GENERATED by script/export-abis.mjs — do not edit.\n` +
    `// Swap this file to point the dApp at a different contract; the UI reads it generically.\n` +
    `export const name = ${JSON.stringify(c.name)};\n` +
    `export const abi = ${JSON.stringify(abi, null, 2)};\n` +
    `export const selectors = ${JSON.stringify(selectors, null, 2)};\n` +
    `export default { name, abi, selectors };\n`;
  writeFileSync(join(ABI_DIR, `${c.name}.abi.js`), body);
  manifest.contracts.push({ name: c.name, abiModule: `abis/${c.name}.abi.js`, deploymentKey: c.name });
  console.log(`[export-abis] abis/${c.name}.abi.js  (${abi.length} entries, ${Object.keys(selectors).length} selectors)`);
}

// Lift deployed addresses from the latest broadcasts, keyed by chainId.
function harvestDeployments() {
  if (!existsSync(BROADCAST)) return;
  for (const scriptDir of readdirSync(BROADCAST)) {
    const sdir = join(BROADCAST, scriptDir);
    let chains = [];
    try { chains = readdirSync(sdir); } catch { continue; }
    for (const chainId of chains) {
      const runLatest = join(sdir, chainId, "run-latest.json");
      if (!existsSync(runLatest)) continue;
      const run = JSON.parse(readFileSync(runLatest, "utf8"));
      const depPath = join(DEPLOY_DIR, `${chainId}.json`);
      const deployments = existsSync(depPath) ? JSON.parse(readFileSync(depPath, "utf8")) : {};
      for (const tx of run.transactions || []) {
        if (tx.transactionType === "CREATE" && tx.contractName && tx.contractAddress) {
          deployments[tx.contractName] = tx.contractAddress;
        }
      }
      writeFileSync(depPath, JSON.stringify(deployments, null, 2) + "\n");
      console.log(`[export-abis] deployments/${chainId}.json  ${JSON.stringify(deployments)}`);
    }
  }
}
harvestDeployments();

writeFileSync(join(DAPP, "contracts.json"), JSON.stringify(manifest, null, 2) + "\n");
console.log(`[export-abis] contracts.json  (${manifest.contracts.length} contracts) — done`);
