"""
RAGE: Retrieval Augmented Generative Engine

A comprehensive system for ingesting, indexing, and retrieving data for context-aware generation.
Supports file ingestion, document processing, and intelligent retrieval for LLM context.
"""

from .ingestion import IngestionEngine
from .retrieval import RetrievalEngine
from .indexing import IndexingEngine
from .storage import StorageEngine


# ─── External LLM-ingestion convention ──────────────────────────────────
# Per llmstxt.org, hosts may publish a /llms.txt sitemap for LLM
# ingestion. The file lists every public post with title + URL +
# description — a clean substitute for crawling sitemap.xml.
#
# Known instances:
#   - https://rage.pythai.net/llms.txt  — auto-generated by the
#     Hostinger Tools Plugin; updates as the operator publishes via the
#     wordpress.agent + AuthorAgent pipeline. This is the canonical
#     surface for ingesting mindX-published rage content into other
#     LLM stacks.
#
# Pattern: format the convention with a host to get a real URL.
#   url = LLMSTXT_CONVENTION_TEMPLATE.format(host="rage.pythai.net")
LLMSTXT_CONVENTION_TEMPLATE = "https://{host}/llms.txt"

LLMSTXT_KNOWN_HOSTS = (
    "rage.pythai.net",
)


__all__ = [
    "IngestionEngine",
    "RetrievalEngine",
    "IndexingEngine",
    "StorageEngine",
    "LLMSTXT_CONVENTION_TEMPLATE",
    "LLMSTXT_KNOWN_HOSTS",
]


