# agents/learning/improvement_journal.py
"""
Improvement Journal — mindX documents its own evolution.

Periodically generates docs/IMPROVEMENT_JOURNAL.md from:
  - Campaign history (SEA audit-driven campaigns)
  - Gödel decisions (autonomous choice audit trail)
  - Memory summaries (system health, patterns)
  - Inference discovery (provider reliability over time)
  - Belief system growth

This is how mindX keeps a historical record of its self-improvements.
Each entry is timestamped, explained, and attributed to the agent that drove it.

Usage:
  journal = ImprovementJournal()
  await journal.write_entry()        # Write current state snapshot
  await journal.run_periodic(3600)   # Write every hour
"""

import json
import asyncio
from pathlib import Path
from datetime import datetime, timezone
from typing import Optional, Dict, Any, List

from utils.config import PROJECT_ROOT
from utils.logging_config import get_logger

logger = get_logger(__name__)

JOURNAL_PATH = PROJECT_ROOT / "docs" / "IMPROVEMENT_JOURNAL.md"
JOURNAL_HEADER = """# mindX Improvement Journal

> Auto-generated by mindX. Each entry documents a self-improvement cycle,
> an autonomous decision, or a system evolution event. This is the living
> record of a self-improving system — written by the system itself.
>
> **Read from bottom to top for chronological order.**

---

"""


class ImprovementJournal:

    def __init__(self):
        self.journal_path = JOURNAL_PATH
        self._ensure_journal()

    def _ensure_journal(self):
        """Create journal file with header if it doesn't exist."""
        if not self.journal_path.exists():
            self.journal_path.parent.mkdir(parents=True, exist_ok=True)
            self.journal_path.write_text(JOURNAL_HEADER, encoding="utf-8")

    def _read_journal(self) -> str:
        if self.journal_path.exists():
            return self.journal_path.read_text(encoding="utf-8")
        return JOURNAL_HEADER

    def _append_entry(self, entry: str):
        """Append an entry to the journal."""
        current = self._read_journal()
        # Insert after header (after the first ---)
        parts = current.split("---\n", 1)
        if len(parts) == 2:
            updated = parts[0] + "---\n\n" + entry + "\n" + parts[1]
        else:
            updated = current + "\n" + entry
        self.journal_path.write_text(updated, encoding="utf-8")

    async def write_entry(self) -> Dict[str, Any]:
        """
        Generate and write a journal entry from current system state.
        Pulls from all available data sources.
        """
        now = datetime.now(timezone.utc)
        ts = now.strftime("%Y-%m-%d %H:%M UTC")
        sections = []
        stats = {}

        # 1. System health
        try:
            from agents.memory_agent import MemoryAgent
            ma = MemoryAgent()
            health = ma.get_system_health_summary()
            stats["stm_records"] = health.get("total_memories", 0)
            stats["agents_active"] = health.get("active_agents", 0)
        except Exception:
            pass

        # 2. Beliefs
        beliefs_path = PROJECT_ROOT / "data" / "memory" / "beliefs.json"
        belief_count = 0
        new_beliefs = []
        try:
            if beliefs_path.exists():
                bd = json.loads(beliefs_path.read_text())
                belief_count = len(bd)
                # Find beliefs that aren't just identity mappings
                for k, v in bd.items():
                    if "identity.map" not in k:
                        new_beliefs.append(f"  - `{k}`: {v.get('value', '')}")
        except Exception:
            pass
        stats["beliefs"] = belief_count

        # 3. Gödel decisions
        godel_path = PROJECT_ROOT / "data" / "logs" / "godel_choices.jsonl"
        recent_decisions = []
        try:
            if godel_path.exists():
                lines = [l for l in godel_path.read_text().strip().split("\n") if l.strip()]
                for line in lines[-5:]:
                    try:
                        g = json.loads(line)
                        agent = g.get("source_agent", "unknown")
                        ctype = g.get("choice_type", "")
                        chosen = str(g.get("chosen", ""))[:120]
                        rationale = g.get("rationale", "")[:120]
                        if chosen or rationale:
                            recent_decisions.append(
                                f"  - **{agent}** ({ctype}): {chosen}"
                                + (f" — *{rationale}*" if rationale else "")
                            )
                    except Exception:
                        continue
        except Exception:
            pass

        # 4. Campaign history
        campaign_dir = PROJECT_ROOT / "data" / "sea_campaign_history"
        recent_campaigns = []
        try:
            if campaign_dir.exists():
                for f in sorted(campaign_dir.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True)[:3]:
                    try:
                        campaigns = json.loads(f.read_text())
                        if isinstance(campaigns, list):
                            for c in campaigns[-2:]:
                                status = c.get("overall_campaign_status", "unknown")
                                msg = c.get("final_message", "")[:150]
                                run_id = c.get("campaign_run_id", "?")
                                recent_campaigns.append(f"  - `{run_id}` — **{status}**: {msg}")
                    except Exception:
                        continue
        except Exception:
            pass

        # 5. Improvement backlog
        backlog_path = PROJECT_ROOT / "data" / "improvement_backlog.json"
        backlog_count = 0
        backlog_top = []
        try:
            if backlog_path.exists():
                bl = json.loads(backlog_path.read_text())
                if isinstance(bl, list):
                    backlog_count = len(bl)
                    for item in sorted(bl, key=lambda x: x.get("priority", 0), reverse=True)[:3]:
                        target = item.get("target_component_path", "?")
                        suggestion = item.get("suggestion", "")[:100]
                        backlog_top.append(f"  - [{item.get('priority', '?')}] `{target}`: {suggestion}")
        except Exception:
            pass

        # 6. Recent actions from pgvector
        recent_actions = []
        try:
            from agents import memory_pgvector as _mpg
            actions = await _mpg.get_recent_actions(limit=5)
            for a in actions:
                status = a.get("status", "?")
                desc = a.get("description", "")[:100]
                src = a.get("source", "")
                agent = a.get("agent_id", "?")
                recent_actions.append(f"  - **{status}** ({agent}, {src}): {desc}")
        except Exception:
            pass

        # 7. Inference status
        inference_info = ""
        try:
            from llm.inference_discovery import InferenceDiscovery
            disc = await InferenceDiscovery.get_instance()
            summary = disc.status_summary()
            avail = summary.get("available", 0)
            total = summary.get("total_sources", 0)
            local = summary.get("local_inference", False)
            inference_info = f"{avail}/{total} sources available" + (" (local inference active)" if local else " (cloud only)")
        except Exception:
            pass

        # Build the entry
        entry = f"## {ts}\n\n"
        entry += f"**System snapshot**: {stats.get('stm_records', '?')} memories, "
        entry += f"{belief_count} beliefs, {backlog_count} backlog items, {inference_info}\n\n"

        if recent_actions:
            entry += "### Actions\n\n"
            entry += "\n".join(recent_actions) + "\n\n"

        if recent_decisions:
            entry += "### Autonomous Decisions\n\n"
            entry += "\n".join(recent_decisions) + "\n\n"

        if recent_campaigns:
            entry += "### Improvement Campaigns\n\n"
            entry += "\n".join(recent_campaigns) + "\n\n"

        if new_beliefs:
            entry += "### New Beliefs (Learned Knowledge)\n\n"
            entry += "\n".join(new_beliefs) + "\n\n"

        if backlog_top:
            entry += "### Priority Backlog\n\n"
            entry += "\n".join(backlog_top) + "\n\n"

        # Always add a one-line summary
        if not recent_decisions and not recent_campaigns and not new_beliefs:
            entry += "*System operating nominally. No new decisions, campaigns, or learnings this cycle.*\n\n"

        self._append_entry(entry)
        logger.info(f"ImprovementJournal: entry written at {ts}")

        return {
            "timestamp": ts,
            "beliefs": belief_count,
            "decisions": len(recent_decisions),
            "campaigns": len(recent_campaigns),
            "backlog": backlog_count,
        }

    async def write_moment(self, event: str, detail: str = ""):
        """Write a brief journal entry for a significant moment (kairos, not chronos).
        Called by agents when something meaningful happens — not on a timer."""
        now = datetime.now(timezone.utc)
        ts = now.strftime("%Y-%m-%d %H:%M UTC")
        entry = f"## {ts}\n\n**{event}**"
        if detail:
            entry += f" — {detail}"
        entry += "\n\n"
        self._append_entry(entry)
        logger.info(f"ImprovementJournal: moment recorded — {event}")
        return {"timestamp": ts, "event": event}

    async def run_periodic(self, interval_seconds: int = 3600):
        """Write a journal entry when meaningful state changes occur.
        Checks on an interval but only writes if something changed (kairos over chronos)."""
        _last_belief_count = 0
        _last_action_count = 0
        _last_decision_count = 0
        while True:
            try:
                # Gather current state
                result = await self.write_entry()
                current_beliefs = result.get("beliefs", 0)
                current_decisions = result.get("decisions", 0)
                current_campaigns = result.get("campaigns", 0)
                # Only write if something meaningful changed
                has_change = (current_beliefs != _last_belief_count or
                              current_decisions > 0 or current_campaigns > 0)
                if has_change:
                    _last_belief_count = current_beliefs
                    _last_decision_count = current_decisions
                    logger.info(f"ImprovementJournal: state changed, entry written")
                else:
                    logger.debug(f"ImprovementJournal: no meaningful change, skipping")
            except Exception as e:
                logger.warning(f"ImprovementJournal periodic write failed: {e}")
            await asyncio.sleep(interval_seconds)
