// SPDX-License-Identifier: Apache-2.0
// GENERATED by script/export-abis.mjs — contract catalogue for the dApp.
// loadAbi(name) dynamically imports the per-contract module (abi-as-stylesheet).
export const CONTRACTS = [
  {
    "name": "BankonSubnameRegistrar",
    "title": "Subname Registrar",
    "category": "registrar",
    "deploymentKey": "subnameRegistrar"
  },
  {
    "name": "BankonEthRegistrar",
    "title": ".eth Registrar",
    "category": "registrar",
    "deploymentKey": "ethRegistrar"
  },
  {
    "name": "BankonDomainHosting",
    "title": "Domain Hosting",
    "category": "registrar",
    "deploymentKey": "domainHosting"
  },
  {
    "name": "BankonSubnameResolver",
    "title": "Resolver",
    "category": "resolver",
    "deploymentKey": "resolver"
  },
  {
    "name": "BankonSubnameResolverV2",
    "title": "Resolver V2",
    "category": "resolver",
    "deploymentKey": "resolverV2"
  },
  {
    "name": "BankonPriceOracle",
    "title": "Price Oracle",
    "category": "pricing",
    "deploymentKey": "priceOracle"
  },
  {
    "name": "BankonReputationGate",
    "title": "Reputation Gate",
    "category": "access",
    "deploymentKey": "reputationGate"
  },
  {
    "name": "BankonPaymentRouter",
    "title": "Payment Router",
    "category": "payment",
    "deploymentKey": "paymentRouter"
  },
  {
    "name": "BankonInftAdapter",
    "title": "iNFT Adapter",
    "category": "inft",
    "deploymentKey": "inftAdapter"
  },
  {
    "name": "BankonX402Attestor",
    "title": "x402 Attestor",
    "category": "payment",
    "deploymentKey": "x402Attestor"
  },
  {
    "name": "X402Receipt",
    "title": "x402 Receipt",
    "category": "payment",
    "deploymentKey": "x402Receipt"
  },
  {
    "name": "BankonAgenticPlaceHook",
    "title": "AgenticPlace Hook",
    "category": "listing",
    "deploymentKey": "agenticPlaceHook"
  },
  {
    "name": "AgentRegistry",
    "title": "Agent Registry",
    "category": "identity",
    "deploymentKey": "agentRegistry"
  },
  {
    "name": "BankonAuthGate",
    "title": "Auth Gate",
    "category": "identity",
    "deploymentKey": "authGate"
  },
  {
    "name": "SoulBadger",
    "title": "SoulBadger",
    "category": "identity",
    "deploymentKey": "soulBadger"
  },
  {
    "name": "BankonOffchainRegistrar",
    "title": "Offchain Registrar",
    "category": "offchain",
    "deploymentKey": "offchainRegistrar"
  },
  {
    "name": "BankonOffchainResolver",
    "title": "Offchain Resolver",
    "category": "offchain",
    "deploymentKey": "offchainResolver"
  },
  {
    "name": "bankon_inft_subname",
    "title": "iNFT (Mode A unified)",
    "category": "inft7857",
    "deploymentKey": "inftUnified"
  },
  {
    "name": "bankon_inft_extension",
    "title": "iNFT (Mode B parallel)",
    "category": "inft7857",
    "deploymentKey": "inftParallel"
  },
  {
    "name": "bankon_inft_registrar",
    "title": "iNFT Registrar",
    "category": "inft7857",
    "deploymentKey": "inftRegistrar"
  },
  {
    "name": "bankon_inft_oracle",
    "title": "iNFT Verifier (oracle)",
    "category": "inft7857",
    "deploymentKey": "inftOracle"
  },
  {
    "name": "bankon_tba_account",
    "title": "ERC-6551 TBA account",
    "category": "inft7857",
    "deploymentKey": "tbaImpl"
  },
  {
    "name": "bankon_tba_registry_proxy",
    "title": "TBA registry proxy",
    "category": "inft7857",
    "deploymentKey": "tbaRegistryProxy"
  },
  {
    "name": "bankon_agent_market",
    "title": "Agent Marketspace",
    "category": "arc",
    "deploymentKey": "agentMarket"
  },
  {
    "name": "AgentReputationRegistry",
    "title": "Agent Reputation",
    "category": "arc",
    "deploymentKey": "agentReputation"
  },
  {
    "name": "AgenticMarketplaceEscrow",
    "title": "Marketplace Escrow",
    "category": "arc",
    "deploymentKey": "agentEscrow"
  },
  {
    "name": "SubscriptionManager",
    "title": "Subscriptions",
    "category": "arc",
    "deploymentKey": "subscriptions"
  },
  {
    "name": "scientific_token",
    "title": "SCIENTIFIC token",
    "category": "cp2048",
    "deploymentKey": "scientific"
  },
  {
    "name": "rake",
    "title": "RAKE collector",
    "category": "cp2048",
    "deploymentKey": "rakeCollector"
  },
  {
    "name": "bankon_oracle",
    "title": "Pair-price oracle",
    "category": "cp2048",
    "deploymentKey": "bankonOracle"
  },
  {
    "name": "bankon_autoconvert",
    "title": "Auto-convert router",
    "category": "cp2048",
    "deploymentKey": "autoconvert"
  },
  {
    "name": "bridge_collect",
    "title": "Bridge-collect (GLMR)",
    "category": "cp2048",
    "deploymentKey": "bridgeCollect"
  },
  {
    "name": "bankon_gas_service",
    "title": "Gas-as-a-service",
    "category": "cp2048",
    "deploymentKey": "gasService"
  },
  {
    "name": "treasury",
    "title": "Treasury vault",
    "category": "cp2048",
    "deploymentKey": "treasury"
  },
  {
    "name": "remittance",
    "title": "Remittance",
    "category": "cp2048",
    "deploymentKey": "remittance"
  }
];
export const byKey = Object.fromEntries(CONTRACTS.map((c) => [c.deploymentKey, c]));
export async function loadAbi(name) { return (await import(`./${name}.abi.js`)).ABI; }
