/**
 * provenance.js — consent, custody, and the signed manifest that travels with
 * every aivatar artifact good enough to be mistaken for a recording.
 *
 * The scientific tier exists to produce faces and voices indistinguishable from
 * reality. That capability is only legitimate — and only usable in media, in
 * court, in an AIML interaction anyone should trust — when the artifact can
 * PROVE what it is. So provenance is not a wrapper bolted on afterwards; it is
 * part of the artifact's identity:
 *
 *   consent()   — a signed attestation that the SUBJECT authorised this clone
 *   custody()   — hash-linked records of every capture/edit/export step
 *   manifest()  — a C2PA-shaped, signable declaration: this is synthetic, made
 *                 by this tool, from these sources, at this fidelity, under this
 *                 consent, with this custody chain
 *   verify()    — recompute every link; a tampered manifest fails loudly
 *
 * Signing is BYO-key: pass `sign(bytes) -> hex` (an EIP-191 signer, the BANKON
 * vault, an HSM). Unsigned manifests are valid objects but `verify()` reports
 * `signed: false` — an unsigned scientific artifact is INCOMPLETE, and
 * PersonaStudio refuses to stamp it.
 *
 * © Professor Codephreak - rage.pythai.net
 */

import { createHash } from 'node:crypto';

const sha = (s) => '0x' + createHash('sha256').update(s).digest('hex');
const canon = (o) => JSON.stringify(o, Object.keys(o).sort());

export const CONSENT_KINDS = Object.freeze([
  'self', // the operator is the subject (cloning yourself — the common case)
  'attested', // a third-party subject who signed an attestation
  'synthetic', // no real subject exists (invented persona — no consent needed)
  'licensed', // rights held under a licence/contract reference
  'public-figure-commentary', // documented lawful basis; still disclosed
]);

/**
 * Consent attestation for cloning a subject.
 * @param {{kind:string, subject?:string, subjectAddress?:string, statement?:string,
 *          reference?:string, at?:string}} c
 */
export function consent(c = {}) {
  if (!CONSENT_KINDS.includes(c.kind)) {
    throw new Error(`provenance: consent.kind must be one of ${CONSENT_KINDS.join('|')}`);
  }
  const record = {
    v: 1,
    kind: 'consent',
    consentKind: c.kind,
    subject: c.subject || null, // a name/handle, or null for synthetic
    subjectAddress: c.subjectAddress || null, // wallet that signed, when attested
    statement:
      c.statement ||
      (c.kind === 'synthetic'
        ? 'No real subject: this persona is invented.'
        : 'The subject authorises the creation and use of this synthetic likeness/voice.'),
    reference: c.reference || null, // contract id, ticket, licence URI
    at: c.at || new Date().toISOString(),
  };
  record.hash = sha(canon(record));
  return record;
}

/** Is this consent sufficient to clone a real person at the given mode? */
export function consentSatisfies(consentRecord, mode) {
  const need = mode === 'basic' ? 'recommended' : 'required';
  if (!consentRecord) return { ok: need === 'recommended', reason: 'no consent record' };
  if (consentRecord.consentKind === 'synthetic') return { ok: true, reason: 'no real subject' };
  if (consentRecord.consentKind === 'attested' && !consentRecord.subjectAddress) {
    return { ok: false, reason: 'attested consent requires the subject signing address' };
  }
  return { ok: true, reason: `consent: ${consentRecord.consentKind}` };
}

/** One hash-linked step in the artifact's life (capture → edit → export). */
export function custodyStep({ action, contentHash, note = null, prev = null, at = null }) {
  if (!action) throw new Error('provenance: custodyStep needs an action');
  const record = {
    v: 1,
    kind: 'custody',
    action, // 'capture' | 'clone' | 'edit' | 'synthesize' | 'export' | …
    contentHash: contentHash || null,
    note,
    prev,
    at: at || new Date().toISOString(),
  };
  record.hash = sha(canon(record));
  return record;
}

/** Append to a chain, linking to the tail. */
export function appendCustody(chain, step) {
  const prev = chain.length ? chain[chain.length - 1].hash : null;
  const linked = custodyStep({ ...step, prev });
  return [...chain, linked];
}

/**
 * The manifest — C2PA-shaped, tool-agnostic, signable.
 * @param {{persona:object, mode:string, realism?:string, measured?:object,
 *          consent?:object, custody?:Array, sources?:Array, generator?:string}} m
 */
export function manifest(m = {}) {
  const body = {
    v: 1,
    kind: 'aivatar-manifest',
    // The declaration. An artifact that can pass for real says so, in bytes.
    declaration: 'SYNTHETIC — this face and/or voice was generated by aivatar.',
    generator: m.generator || 'aivatar',
    createdAt: m.at || new Date().toISOString(),
    persona: {
      hash: m.persona?.hash || null,
      label: m.persona?.label || null,
      modalities: m.persona?.modalities || [],
    },
    fidelity: {
      mode: m.mode,
      realism: m.realism || null,
      measured: m.measured || {},
      // How each number was obtained: 'computed' (this tool measured it) vs
      // 'supplied' (an external rig asserted it). A supplied number is only as
      // good as the signature over this manifest — the record makes that visible.
      measuredSource: m.measuredSource || {},
    },
    consent: m.consent ? { hash: m.consent.hash, kind: m.consent.consentKind } : null,
    sources: (m.sources || []).map((s) => ({ type: s.type, hash: s.hash, note: s.note || null })),
    custodyRoot: m.custody?.length ? m.custody[m.custody.length - 1].hash : null,
    custodyLength: m.custody?.length || 0,
  };
  body.hash = sha(canon(body));
  return { ...body, signature: null, signer: null };
}

/**
 * Sign a manifest. `sign` is any async (message:string) => hex signature.
 * @param {object} man
 * @param {(msg:string)=>Promise<string>|string} sign
 * @param {string} [signer] the signing identity (wallet address / key id)
 */
export async function signManifest(man, sign, signer = null) {
  if (typeof sign !== 'function') throw new Error('provenance: sign must be a function');
  const signature = await sign(man.hash);
  return { ...man, signature, signer };
}

/**
 * Verify a manifest + its custody chain. Recomputes every hash — a single
 * altered byte anywhere fails.
 * @returns {{ok:boolean, signed:boolean, errors:string[]}}
 */
export function verify(man, custody = []) {
  const errors = [];
  if (!man || man.kind !== 'aivatar-manifest') {
    return { ok: false, signed: false, errors: ['not an aivatar manifest'] };
  }
  const { hash, signature, signer, ...body } = man;
  if (sha(canon(body)) !== hash) errors.push('manifest hash mismatch (tampered)');

  let prev = null;
  custody.forEach((step, i) => {
    const { hash: h, ...rest } = step;
    if (sha(canon(rest)) !== h) errors.push(`custody[${i}]: hash mismatch`);
    if (rest.prev !== prev) errors.push(`custody[${i}]: broken link`);
    prev = h;
  });
  if (custody.length && man.custodyRoot !== custody[custody.length - 1].hash) {
    errors.push('custodyRoot does not match the chain tail');
  }
  return { ok: errors.length === 0, signed: !!signature, signer: signer || null, errors };
}

export default { consent, consentSatisfies, custodyStep, appendCustody, manifest, signManifest, verify };
